//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoConversionTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CargoConversionTool.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        internal static string BillingCategory {
            get {
                return ResourceManager.GetString("BillingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        internal static string ChargeCategory {
            get {
                return ResourceManager.GetString("ChargeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        internal static string ClearanceCurrency {
            get {
                return ResourceManager.GetString("ClearanceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect AirWaybill.
        /// </summary>
        internal static string CollectChargeCode {
            get {
                return ResourceManager.GetString("CollectChargeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid AirWaybill.
        /// </summary>
        internal static string PrepaidChargeCode {
            get {
                return ResourceManager.GetString("PrepaidChargeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Memo.
        /// </summary>
        internal static string RejectionMemoChargeCode {
            get {
                return ResourceManager.GetString("RejectionMemoChargeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ST-.
        /// </summary>
        internal static string SandboxPrefix {
            get {
                return ResourceManager.GetString("SandboxPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 724.
        /// </summary>
        internal static string SellerOrganizationID {
            get {
                return ResourceManager.GetString("SellerOrganizationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string ShortBillingCategory {
            get {
                return ResourceManager.GetString("ShortBillingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMLF-.
        /// </summary>
        internal static string XMLPrefix {
            get {
                return ResourceManager.GetString("XMLPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IATA:ISXMLInvoiceV3.2.
        /// </summary>
        internal static string XmlVersion {
            get {
                return ResourceManager.GetString("XmlVersion", resourceCulture);
            }
        }
    }
}
